fn main() {
    populate_configs().unwrap();
    linker_be_nice();
    // make sure linkall.x is the last linker script (otherwise might cause problems with flip-link)
    println!("cargo:rustc-link-arg=-Tlinkall.x");
}

fn linker_be_nice() {
    let args: Vec<String> = std::env::args().collect();
    if args.len() > 1 {
        let kind = &args[1];
        let what = &args[2];

        match kind.as_str() {
            "undefined-symbol" => match what.as_str() {
                what if what.starts_with("_defmt_") => {
                    eprintln!();
                    eprintln!(
                        "💡 `defmt` not found - make sure `defmt.x` is added as a linker script and you have included `use defmt_rtt as _;`"
                    );
                    eprintln!();
                }
                "_stack_start" => {
                    eprintln!();
                    eprintln!("💡 Is the linker script `linkall.x` missing?");
                    eprintln!();
                }
                what if what.starts_with("esp_rtos_") => {
                    eprintln!();
                    eprintln!(
                        "💡 `esp-radio` has no scheduler enabled. Make sure you have initialized `esp-rtos` or provided an external scheduler."
                    );
                    eprintln!();
                }
                "embedded_test_linker_file_not_added_to_rustflags" => {
                    eprintln!();
                    eprintln!(
                        "💡 `embedded-test` not found - make sure `embedded-test.x` is added as a linker script for tests"
                    );
                    eprintln!();
                }
                "free"
                | "malloc"
                | "calloc"
                | "get_free_internal_heap_size"
                | "malloc_internal"
                | "realloc_internal"
                | "calloc_internal"
                | "free_internal" => {
                    eprintln!();
                    eprintln!(
                        "💡 Did you forget the `esp-alloc` dependency or didn't enable the `compat` feature on it?"
                    );
                    eprintln!();
                }
                _ => (),
            },
            // we don't have anything helpful for "missing-lib" yet
            _ => {
                std::process::exit(1);
            }
        }

        std::process::exit(0);
    }

    println!(
        "cargo:rustc-link-arg=-Wl,--error-handling-script={}",
        std::env::current_exe().unwrap().display()
    );
}

fn populate_configs() -> std::io::Result<()> {
    use std::io::Write;

    let update_sec: u64 = env!("UPDATE_SEC").parse().unwrap_or(2);
    let lat: f64 = env!("LAT").parse().unwrap_or(-33.8651);
    let lon: f64 = env!("LON").parse().unwrap_or(151.2099);

    // find timezone offset seconds by lat and lon
    let tz_finder = tzf_rs::DefaultFinder::new();
    let tz_str = tz_finder.get_tz_name(lon, lat);
    let tz = tz::TimeZone::from_posix_tz(tz_str).unwrap_or(tz::TimeZone::utc());

    // find DST rules of the timezone
    let dst_transit_table_start_year = time::UtcDateTime::now().year();
    let dst_transit_table: Vec<DstRule> = (dst_transit_table_start_year..=2050)
        .filter_map(|yr| DstRule::find_dst_rules(yr, &tz))
        .collect();
    let dst_transit_table = DstRules(dst_transit_table);

    // standard timezone offset in seconds without DST shifts
    let tz_offset_secs = tz
        .find_current_local_time_type()
        .map_or(0, |tz_local_time_type| {
            if tz_local_time_type.is_dst() {
                tz_local_time_type.ut_offset() - 3600 // push back 1 hour to the standard timezone offset due to DST
            } else {
                tz_local_time_type.ut_offset()
            }
        });

    let mut config_rs = std::fs::File::options()
        .write(true)
        .create(true)
        .truncate(true)
        .open("src/config.rs")?;

    writeln!(
        config_rs,
        r#"//! Code generated by build.rs, DO NOT EDIT!!
//!
pub const UPDATE_SEC: u64 = {update_sec};
pub const LAT: f64 = {lat};
pub const LON: f64 = {lon}; // {tz_str}

/// standard time zone offset reference to UTC, without DST rules
pub const TZ_OFFSET: time::UtcOffset = time::UtcOffset::from_whole_seconds({tz_offset_secs}).unwrap_or(time::UtcOffset::UTC);
/// time zone offset when DST enabled
pub const TZ_OFFSET_DST: time::UtcOffset = time::UtcOffset::from_whole_seconds({tz_offset_secs} + 3600).unwrap_or(time::UtcOffset::UTC);

/// DST rules, (start, end)
pub const TZ_DST_RULES: &[(i64, i64)] = &{dst_transit_table};

/// the year of DST rules index 0
pub const TZ_DST_RULES_START_YEAR: usize = {dst_transit_table_start_year};


"#
    )?;

    Ok(())
}

fn time_weekday(weekday: u8) -> time::Weekday {
    match weekday {
        0 => time::Weekday::Sunday,
        1 => time::Weekday::Monday,
        2 => time::Weekday::Tuesday,
        3 => time::Weekday::Wednesday,
        4 => time::Weekday::Thursday,
        5 => time::Weekday::Friday,
        6 => time::Weekday::Saturday,
        _ => time::Weekday::Sunday,
    }
}

struct DstRule {
    start: time::UtcDateTime,
    end: time::UtcDateTime,
}

impl DstRule {
    /// find dst start and end datetime of the year in UTC
    fn find_dst_rules(year: i32, tz: &tz::TimeZone) -> Option<Self> {
        use time::{Date, SignedDuration, Time};
        use tz::timezone::{RuleDay, TransitionRule};

        let mut tz_dst_start = None;
        let mut tz_dst_end = None;

        // POSIX TZ are month-week-day representation for DST rules
        if let Some(TransitionRule::Alternate(dst_rule)) = tz.as_ref().extra_rule()
            && let (RuleDay::MonthWeekDay(dst_start), RuleDay::MonthWeekDay(dst_end)) =
                (dst_rule.dst_start(), dst_rule.dst_end())
        {
            // DST start rule in UTC
            let first_day =
                time::Date::from_calendar_date(year, dst_start.month().try_into().unwrap(), 1)
                    .unwrap_or(time::Date::MIN);
            let dst_start =
                first_day.nth_next_occurrence(time_weekday(dst_start.week_day()), dst_start.week());
            let dst_start = dst_start.with_time(Time::MIDNIGHT)
                - SignedDuration::seconds(dst_rule.std().ut_offset() as i64)
                + SignedDuration::seconds(dst_rule.dst_start_time() as i64);
            tz_dst_start = Some(dst_start.as_utc());

            // DST end rule in UTC
            let first_day = Date::from_calendar_date(year, dst_end.month().try_into().unwrap(), 1)
                .unwrap_or(Date::MIN);
            let dst_end =
                first_day.nth_next_occurrence(time_weekday(dst_end.week_day()), dst_end.week());
            let dst_end = dst_end.with_time(Time::MIDNIGHT)
                - SignedDuration::seconds(dst_rule.std().ut_offset() as i64)
                + SignedDuration::seconds(dst_rule.dst_start_time() as i64)
                - SignedDuration::seconds(3600); // push back 1 hour because the DST transit rule is in the current local time 
            tz_dst_end = Some(dst_end.as_utc());
        }

        if let (Some(tz_dst_start), Some(tz_dst_end)) = (tz_dst_start, tz_dst_end) {
            Some(Self {
                start: tz_dst_start,
                end: tz_dst_end,
            })
        } else {
            None
        }
    }
}
struct DstRules(Vec<DstRule>);

impl std::ops::Deref for DstRules {
    type Target = [DstRule];

    fn deref(&self) -> &Self::Target {
        self.0.as_ref()
    }
}

impl std::fmt::Display for DstRules {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        writeln!(f, "[")?;
        self.iter().for_each(|dr| {
            let start_ts = dr.start.unix_timestamp();
            let end_ts = dr.end.unix_timestamp();

            let _ = writeln!(
                f,
                "   ({}, {}), // ({}, {})",
                start_ts, end_ts, dr.start, dr.end
            );
        });

        write!(f, "]")
    }
}
