fn main() {
    populate_configs().unwrap();
    linker_be_nice();
    // make sure linkall.x is the last linker script (otherwise might cause problems with flip-link)
    println!("cargo:rustc-link-arg=-Tlinkall.x");
}

fn linker_be_nice() {
    let args: Vec<String> = std::env::args().collect();
    if args.len() > 1 {
        let kind = &args[1];
        let what = &args[2];

        match kind.as_str() {
            "undefined-symbol" => match what.as_str() {
                what if what.starts_with("_defmt_") => {
                    eprintln!();
                    eprintln!(
                        "💡 `defmt` not found - make sure `defmt.x` is added as a linker script and you have included `use defmt_rtt as _;`"
                    );
                    eprintln!();
                }
                "_stack_start" => {
                    eprintln!();
                    eprintln!("💡 Is the linker script `linkall.x` missing?");
                    eprintln!();
                }
                what if what.starts_with("esp_rtos_") => {
                    eprintln!();
                    eprintln!(
                        "💡 `esp-radio` has no scheduler enabled. Make sure you have initialized `esp-rtos` or provided an external scheduler."
                    );
                    eprintln!();
                }
                "embedded_test_linker_file_not_added_to_rustflags" => {
                    eprintln!();
                    eprintln!(
                        "💡 `embedded-test` not found - make sure `embedded-test.x` is added as a linker script for tests"
                    );
                    eprintln!();
                }
                "free"
                | "malloc"
                | "calloc"
                | "get_free_internal_heap_size"
                | "malloc_internal"
                | "realloc_internal"
                | "calloc_internal"
                | "free_internal" => {
                    eprintln!();
                    eprintln!(
                        "💡 Did you forget the `esp-alloc` dependency or didn't enable the `compat` feature on it?"
                    );
                    eprintln!();
                }
                _ => (),
            },
            // we don't have anything helpful for "missing-lib" yet
            _ => {
                std::process::exit(1);
            }
        }

        std::process::exit(0);
    }

    println!(
        "cargo:rustc-link-arg=-Wl,--error-handling-script={}",
        std::env::current_exe().unwrap().display()
    );
}

fn populate_configs() -> std::io::Result<()> {
    use std::io::Write;

    let update_sec: u64 = env!("UPDATE_SEC").parse().unwrap_or(2);
    let lat: f64 = env!("LAT").parse().unwrap_or(-33.8651);
    let lon: f64 = env!("LON").parse().unwrap_or(151.2099);

    // TODO: auto timezone selection from given latitude and longitude
    let tz_offset_hrs: u8 = env!("TZ_OFFSET_HOURS").parse().unwrap_or(10);
    let tz_offset_minutes: u8 = env!("TZ_OFFSET_MINUTES").parse().unwrap_or(0);

    let mut config_rs = std::fs::File::options()
        .write(true)
        .create(true)
        .truncate(true)
        .open("src/config.rs")?;

    writeln!(
        config_rs,
        r#"// Code generated by build.rs, DO NOT EDIT!!

pub const UPDATE_SEC: u64 = {update_sec};
pub const LAT: f64 = {lat};
pub const LON: f64 = {lon};
pub const TZ_OFFSET_HOURS: u8 = {tz_offset_hrs};
pub const TZ_OFFSET_MINUTES: u8 = {tz_offset_minutes};"#
    )?;

    Ok(())
}
