[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor --chip esp32"

[env]
WIFI_SSID = ""
WIFI_PSWD = ""
NTP_SERVER="pool.ntp.org"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["alloc", "core"]
